spring:
  application:
      name: demoservice
  datasource:
    url: ${DB_URL}   #jdbc:postgresql://localhost:5432/conference_app
    username: #comment if deploying in heroku postgres
    password: #comment if deploying in heroku Welcome
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true  
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
  

demoservice:
   user:
     details:
       role: user
       credential:
         dhruba: magora
         dayita: aroit
         mommy: daddy

app:
  version: 1.0.0
  
server:
   port: 8080
logging:
   file: /logs/demoservice.log
   
---
spring:
   profiles: dev
   application:
     name: demoservice
server:
   port: 5000
logging:
   file: /logs/demoservice.log
   level:
     org: #WARN
---
spring:
   profiles: prod
   application:
     name: demoservice
server:
   port: 7070
logging:
   file: /logs/demoservice.log