spring:
   application:
      name: demoservice
server:
   port: 8080
logging:
   file: /logs/demoservice.log

---
spring:
   profiles: dev
   application:
     name: demoservice
server:
   port: 9090
logging:
   file: /logs/demoservice.log
---
spring:
   profiles: dev
   application:
     name: demoservice
server:
   port: 7070
logging:
   file: /logs/demoservice.log