spring:
   application:
      name: demoservice
demoservice:
   user:
     details:
       role: user
       credential:
         dhruba: magora
         dayita: aroit
         mommy: daddy
server:
   port: 8080
logging:
   file: /logs/demoservice.log

---
spring:
   profiles: dev
   application:
     name: demoservice
server:
   port: 9090
logging:
   file: /logs/demoservice.log
---
spring:
   profiles: dev
   application:
     name: demoservice
server:
   port: 7070
logging:
   file: /logs/demoservice.log