spring:
  application:
      name: demoservice
  datasource:
    url: jdbc:postgresql://localhost:5432/conference_app
    username: postgres
    password: Welcome
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true  
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
  

demoservice:
   user:
     details:
       role: user
       credential:
         dhruba: magora
         dayita: aroit
         mommy: daddy

server:
   port: 8080
logging:
   file: /logs/demoservice.log
   
---
spring:
   profiles: dev
   application:
     name: demoservice
server:
   port: 9090
logging:
   file: /logs/demoservice.log
---
spring:
   profiles: prod
   application:
     name: demoservice
server:
   port: 7070
logging:
   file: /logs/demoservice.log